version: "3"
services:
  web:
    container_name: nodejs
    image: node:12
    volumes:
      - ./src:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run start"
    depends_on:
      - db
    ports:
      - 80:3000
  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: anraku
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: express-sample
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - ./mysql/data:/var/lib/mysql